### ISSUE TITLE
Slack Notification has no text

### ISSUE THREAD

**Issue by EdwinRozario** [boost/slack-code-reviews#9]
Since the addition of dev Avatars to the slack message, the notification shows `This content can't be displayed`.  Probably fixable by tweaking the payload to Slack.

https://stackoverflow.com/questions/56317962/message-notifications-produce-this-content-cant-be-displayed

**Comment by paul-mesnilgrente** [comment]
That's added to the backlog :) Oli mentioned it before.

**Comment by paul-mesnilgrente** [comment]
That's fixed now. I need to deploy :)
